# Generated by Django 3.1.4 on 2020-12-05 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
